config/routes.rb
Rails.application.routes.draw do
  root 'products#new'
  get 'legal' => 'static_pages#legal', as: :legal
  get '/products(.:format)' => 'products#index', as: :products
  post '/products(.:format)' => 'products#create'
  get '/products/new(.:format)' => 'products#new', as: :new_product
  get '/products/:token/edit(.:format)' => 'products#edit', as: :edit_product
  get '/products/:token(.:format)' => 'products#show', as: :product
  patch '/products/:token(.:format)' => 'products#update'
  put '/products/:token(.:format)' => 'products#update'
  delete '/products/:token(.:format)' => 'products#destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_create :generate_token
  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(4, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/cqPX
  # GET /products/cqPX.json
  def show
    @product = Product.where(token: params[:token]).first
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/cqPX/edit
  def edit
    @product = Product.where(token: params[:token]).first
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        redirect_to "/products/#{@product.token}", notice: 'Product was successfully created.'
        # format.html { redirect_to @product, notice: 'Product was successfully created.' }
        # format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/cqPX
  # PATCH/PUT /products/cqPX.json
  def update
    @product = Product.where(id: params[:token]).first
    redirect_to "/products/#{@product.token}", notice: 'Product was successfully created.'
    # respond_to do |format|
    #   if @product.update(product_params)
    #     # format.html { redirect_to @product, notice: 'Product was successfully updated.' }
    #     # format.json { render :show, status: :ok, location: @product }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @product.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /products/cqPX
  # DELETE /products/cqPX.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.where(token: params[:token]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :public_address)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def legal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body style="background: url(http://subtlepatterns.com/patterns/gradient_squares.png);">

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :public_address %><br>
    <%= f.text_field :public_address %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="row">
	<div class="large-8 large-offset-2 columns">
		<div class="panel small-text-center">
		<%= render 'form' %>
		<%= link_to 'Terms and conditions', legal_path %>	
		</div>
	</div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/legal.html.erb
<h1>Legal disclaimer</h1>